name: dino_game_v2
description: "A Flutter game inspired by the classic Dino Runner with modern features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # Storage
  shared_preferences: ^2.2.2

  # Audio
  audioplayers: ^3.0.0  # Downgraded to work with flame_audio
  flame_audio: ^1.4.0   # Stable version

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_analytics: ^11.4.6     # ✅ Compatible avec firebase_core ^3.13.0
  firebase_crashlytics: ^4.3.6    # ✅ Compatible avec firebase_core ^3.13.0

  # Internationalization
  intl: ^0.18.1

  # Game Engine
  flame: ^1.10.0  # Reverted to stable version

  # Utilities
  equatable: ^2.0.5
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/animations/
    - assets/icons/
